steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$_IMAGE_URL", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_IMAGE_URL"]
  # Deploy the container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$_CUSTOM_SERVICE_NAME",
        "--image",
        "$_IMAGE_URL",
        "--region",
        "$_REGION",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: "us-central1" # Default region; this can be overridden in the trigger configuration
  _CUSTOM_SERVICE_NAME: "kimball-back-dev" # Default service name; this can be overridden in the trigger configuration
  _CUSTOM_PROJECT_ID: senna-dev-442821" # Default project ID; this can be overridden in the trigger configuration
  _IMAGE_URL: "gcr.io/senna-dev-442821/ezml-fastapi-dev-img" # Default image URL; this can be overridden in the trigger configuration
